name: gaadistand
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  datetime_picker_formfield: ^1.0.0
  shared_preferences: ^0.5.12+2
  firebase_core: ^0.5.2+1
  firebase_messaging: ^7.0.3
  firebase_crashlytics: ^0.2.3+1
  firebase_analytics: ^6.2.0
  fluttertoast: ^7.1.5
  url_launcher: ^5.7.10
  autocomplete_textfield: ^1.7.3
  http: ^0.12.0+1
  flutter_typeahead: ^1.9.1
  flutter_clean_calendar: ^1.0.2
  intl: ^0.16.1
  date_picker_timeline: ^1.2.1
  flutter_local_notifications: ^1.4.4+1
  device_info: ^0.4.0+1
  progress_dialog: ^1.2.4
  flutter_picker: ^1.1.5
  connectivity: ^0.4.2
  rflutter_alert: ^1.0.2
  get_version: ^0.2.2
  percent_indicator: ^2.1.7
  lottie: ^0.7.0+1
  bubble_bottom_bar: ^1.2.0
  flutter_rounded_progress_bar: ^0.1.2
  timeline_tile: ^1.0.0
  universal_platform: ^0.1.3






  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  share: ^0.6.2+3

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
    - assets/data/country_data.json
    - assets/data/cities_list.json
    - assets/data/localization_en.json
    - assets/data/localization_hi.json
    - assets/images/gadiwala.png
    - assets/images/india_flag_icon.png
    - assets/images/whatsapp.png
    - assets/images/phone.png
    - assets/images/app_logo.png
    - assets/images/made_in_india_image.png
    - assets/images/city_driver_cuate.png
    - assets/images/next_arrow.png
    - assets/images/otp_verify.png
    - assets/images/otp_verify_screen.png
    - assets/images/home_page_icon.png
    - assets/images/plus.png
    - assets/images/search_icon.png
    - assets/images/location_icon.png
    - assets/images/car_type.png
    - assets/images/date_icon.png
    - assets/images/time_icon.png
    - assets/images/rs_icon.png
    - assets/images/search_screen_icon.png
    - assets/images/contact.png
    - assets/images/more_section_img.png
    - assets/images/reward.png
    - assets/images/log_out.png
    - assets/images/invite_friend.png
    - assets/images/terms_and_conditions.png
    - assets/images/support.png
    - assets/images/language.png
    - assets/images/post.png
    - assets/images/invitation.png
    - assets/images/notification.png
    - assets/images/bank.png
    - assets/images/invitation_one.png
    - assets/images/cancel.png
    - assets/images/gift.png
    - assets/images/tutorials.png
    - assets/images/account_history.png

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
